"""fix major_description field name

Revision ID: fb9f0f438d47
Revises: 1d8f5eda13da
Create Date: 2025-02-15 11:53:14.452621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9f0f438d47'
down_revision: Union[str, None] = '1d8f5eda13da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majors', sa.Column('major_description', sa.String(), nullable=True))
    op.drop_column('majors', 'major_decription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majors', sa.Column('major_decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('majors', 'major_description')
    # ### end Alembic commands ###
